### ISSUE TITLE
Relase a version

### ISSUE THREAD

**Issue by meyt** [farhadi/IntlDateTime#10]
Please provide a version, currently on `dev-master` and we must decrease minimum-stability to dev.

**Comment by salarmehr** [comment]
@meyt You can either set:
```
  "minimum-stability": "dev",
  "prefer-stable": true,
```
in the composer.json file or 
```
"farhadi/intl-datetime": "@dev"
```
That set dev stability level only for this package. 

Any way, from his profile, it seems that the original developer is not programming in PHP any more and is interested in  fancier languages (Node.js/Erlang/Elixir) so this package may not be suitable for long term dependence.

**Comment by meyt** [comment]
Yes. but it will be good @farhadi take a look and if cannot support it, note that on README. 
Thank you @salarmehr.
