### ISSUE TITLE
Create the project on packagist

### ISSUE THREAD

**Issue by amiri27** [farhadi/IntlDateTime#3]
Hi..

That would be very nice if you can put the package on packagist so that can be installed through composer..
This is an easy help and if you do not have enough time for that I'm ready to create a PR..

Link:
http://grossi.io/2013/creating-your-first-composer-packagist-package/

Regards,
Mostafa Amiri

**Comment by amiri27** [comment]
Dear Ali,

Do you permit me to fork your library?! I don't see any license type for your very well written library..

Regards,

**Comment by salarmehr** [comment]
@amiri27  It seems Ali is too busy to maintain the code. It's grateful if you keep the class active.

**Comment by amiri27** [comment]
@salarmehr Thanks, I created a pull request an waiting to merge that..
https://github.com/farhadi/IntlDateTime/pull/4

**Comment by farhadi** [comment]
Thanks for your interest and sorry for my laziness ;)

I just put the package on packagist:
https://packagist.org/packages/farhadi/intl-datetime
